MDScreen:
    MDLabel:
        font_name: 'Regular'
        text: 'Điểm số của bạn trong lần luyện tập này!'
        halign: 'center'
        pos_hint: {'center_x': .5, 'center_y': .67}
        font_size: '26sp'


    MDLabel:
        id: score
        font_name: 'Bold'
        text: '06/10 điểm'
        halign: 'center'
        color: '02e687'
        pos_hint: {'center_x': .5, 'center_y': .6}
        font_size: '40sp'


    MDLabel:
        pos_hint: {'center_x': .5, 'center_y': .45}
        font_name: 'Light'
        text: 'Học, học nữa, học mãi.'
        halign: 'center'
        font_size: '20sp'
        color: '838584'

    MDLabel:
        pos_hint: {'center_x': .5, 'center_y': .4}
        font_name: 'Light'
        text: 'Hãy dùng nghị lực và sự kiên trì để đánh bại mọi thứ'
        halign: 'center'
        font_size: '20sp'
        color: '838584'

    MDCard:
        size_hint: None, None
        size: 400, 60
        pos_hint: {'center_x': .5, 'center_y': .1}
        md_bg_color: '02b38f'
        elevation: 3
        radius: [10]
        MDLabel:
            pos_hint: {'center_x': .5, 'center_y': .5}
            font_name: 'Bold'
            color: 'white'
            text: 'Tiếp tục'
            halign: 'center'